--SETTING PRIMARY KEY:

--CÁCH 1:
/*
			CREATE TABLE <TABLE NAME>
		(
			<DATA NAME> <DATA TYPE> <DATA TYPE NUMBER> PRIMARY KEY,
		)
*/
--CÁCH 2:
/*
		CREATE TABLE <TABLE NAME>
		(
			<DATA NAME> <DATA TYPE> <TYPE NUMBER>,

			 PRIMARY KEY (<DATA NAME>)
		)
*?
--CÁCH 3: SAU KHI TẠO BẢNG
/*
		ALTER TABLE <TABLE NAME> ADD PRIMARY KEY (<DATA NAME>)
*/
