
CREATE FUNCTION UFAllNhanVien()
RETURNS TABLE
AS RETURN SELECT * FROM NHANVIEN

SELECT * FROM UFAllNhanVien()
GO

CREATE FUNCTION UCLuongNhanVien(@Manv CHAR(10))
RETURNS INT
AS 
BEGIN
	DECLARE @LUONG INT
	SELECT @LUONG = LUONG FROM NHANVIEN WHERE Manv = @Manv
	RETURN @LUONG
END

SELECT dbo.UCLuongNhanVien('KD001') AS HH

DROP FUNCTION dbo.UCLuongNhanVien
SELECT * FROM dbo.Nhanvien