CREATE DATABASE QLBH
USE QLBH

--	1.TẠO THỦ TỤC CÓ THAM SỐ ĐƯA VÀO LÀ 
MANV, HOTEN, NGAYSINH, GIOTINH, LUONG, MAPHONG, SDT, NGAYBC. 

CREATE TABLE QLNV
(
	MANV NVARCHAR(100) PRIMARY KEY, 
	HOTEN NVARCHAR(100), 
	NGAYSINH DATETIME, 
	GIOTINH NVARCHAR(100),
	LUONG INT, 
	MAPHONG NVARCHAR(100), 
	SDT NVARCHAR(100), 
	NGAYBC DATETIME
)
GO
DROP TABLE QLNV
GO

CREATE PROC SPQLNV
AS
BEGIN
	SELECT * FROM QLNV
END;
EXEC SPQLNV



DROP PROCEDURE SPQLNV