CREATE DATABASE TestReporting
GO

USE TestReporting
GO

CREATE TABLE MonHoc
(
	MaMH INT PRIMARY KEY,
	TenMH NVARCHAR(50) not null
)
GO

CREATE TABLE SinhVien
(
	MaSV INT PRIMARY KEY,
	TenSV NVARCHAR(100) null
)
GO

CREATE TABLE SinhVienDiem
(
	id INT PRIMARY KEY,
	MaSV INT not null,--FK
	MaMH INT not null,--FK
	Diem FLOAT not null

	CONSTRAINT FKMaSV FOREIGN KEY(MaSV) REFERENCES SinhVien(MaSV),
	CONSTRAINT FKMaMH FOREIGN KEY(MaMH) REFERENCES MonHoc(MaMH)
)
GO

--INSERT INTO SINHVIEN VALUES
INSERT INTO SinhVien(MaSV,TenSV) VALUES (1,N'Trần Minh Trí')
INSERT INTO SinhVien(MaSV,TenSV) VALUES (2,N'Trần Công Minh')

--INSERT INTO MonHoc Values
INSERT INTO MonHoc(MaMH,TenMH) VALUES (1,N'Toán')
INSERT INTO MonHoc(MaMH,TenMH) VALUES (2,N'Lý')
INSERT INTO MonHoc(MaMH,TenMH) VALUES (3,N'Hóa')

--INSERT INTO SinhVienDiem Values
INSERT INTO SinhVienDiem(id,MaSV,MaMH,Diem) VALUES (1,1,1,5)
INSERT INTO SinhVienDiem(id,MaSV,MaMH,Diem) VALUES (2,1,3,7)
INSERT INTO SinhVienDiem(id,MaSV,MaMH,Diem) VALUES (3,2,2,9)
INSERT INTO SinhVienDiem(id,MaSV,MaMH,Diem) VALUES (4,2,1,10)
INSERT INTO SinhVienDiem(id,MaSV,MaMH,Diem) VALUES (5,2,3,8)

SELECT * FROM MonHoc
SELECT * FROM SinhVien
SELECT * FROM SinhVienDiem

UPDATE SinhVienDiem SET Diem = 10 WHERE MaSV = 1

SELECT sv.MaSV, sv.TenSV, m.TenMH, svd.Diem 
FROM MonHoc AS m, SinhVien AS sv, SinhVienDiem AS svd 
WHERE m.MaMH = svd.MaMH AND sv.MaSV= svd.MaSV
